name: flutter_avif_platform_interface
description: Common platform interface for the flutter_avif plugin.
version: 3.0.0
repository: https://github.com/yekeskin/flutter_avif/tree/main/flutter_avif_platform_interface

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  ffi: ^2.1.3
  protobuf: ^3.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  ffigen: ^14.0.1